import React from 'react';

interface AINotificationProps {
  userName: string;
  notificationType: 'email_analyzed' | 'reply_generated' | 'priority_alert' | 'summary_ready';
  emailSubject: string;
  emailFrom: string;
  aiSummary: string;
  suggestedAction: string;
  confidence: number;
  dashboardUrl: string;
  unsubscribeUrl: string;
}

export const AINotification: React.FC<AINotificationProps> = ({
  userName,
  notificationType,
  emailSubject,
  emailFrom,
  aiSummary,
  suggestedAction,
  confidence,
  dashboardUrl,
  unsubscribeUrl,
}) => {
  const getNotificationTitle = () => {
    switch (notificationType) {
      case 'email_analyzed':
        return '📧 Email Analyzed';
      case 'reply_generated':
        return '✍️ Reply Generated';
      case 'priority_alert':
        return '🚨 Priority Alert';
      case 'summary_ready':
        return '📋 Summary Ready';
      default:
        return '🤖 AI Update';
    }
  };

  const getNotificationMessage = () => {
    switch (notificationType) {
      case 'email_analyzed':
        return 'Your AI assistant has analyzed a new email and identified key insights.';
      case 'reply_generated':
        return 'Your AI assistant has generated a thoughtful reply based on the email context.';
      case 'priority_alert':
        return 'An urgent email has been detected that requires your immediate attention.';
      case 'summary_ready':
        return 'A summary of your recent emails is ready for your review.';
      default:
        return 'Your AI assistant has an update for you.';
    }
  };

  const confidenceColor = confidence >= 0.8 ? '#10B981' : confidence >= 0.6 ? '#F59E0B' : '#DC2626';

  return (
    <div className="email-container">
      <div className="header">
        <div className="logo">Super Intelligence</div>
        <div className="tagline">AI-Powered Productivity</div>
      </div>
      
      <div className="content">
        <div className="notification-header">
          <div className="notification-icon">{getNotificationTitle()}</div>
          <h1 className="greeting">Hello, {userName}!</h1>
        </div>
        
        <p className="message">
          {getNotificationMessage()}
        </p>
        
        <div className="email-details">
          <div className="email-info">
            <div className="email-from">
              <strong>From:</strong> {emailFrom}
            </div>
            <div className="email-subject">
              <strong>Subject:</strong> {emailSubject}
            </div>
          </div>
        </div>
        
        <div className="ai-analysis">
          <h3>🤖 AI Analysis</h3>
          <div className="analysis-content">
            <p className="summary">{aiSummary}</p>
            <div className="suggested-action">
              <strong>Suggested Action:</strong> {suggestedAction}
            </div>
          </div>
        </div>
        
        <div className="confidence-meter">
          <div className="confidence-header">
            <span>AI Confidence</span>
            <span className="confidence-score" style={{ color: confidenceColor }}>
              {Math.round(confidence * 100)}%
            </span>
          </div>
          <div className="confidence-bar">
            <div 
              className="confidence-fill"
              style={{ 
                width: `${confidence * 100}%`,
                backgroundColor: confidenceColor
              }}
            />
          </div>
        </div>
        
        <div className="cta-section">
          <a href={dashboardUrl} className="cta-button">
            View in Dashboard
          </a>
        </div>
        
        <div className="quick-actions">
          <h3>Quick Actions</h3>
          <div className="action-buttons">
            <a href={`${dashboardUrl}?action=reply`} className="action-button">
              ✍️ Generate Reply
            </a>
            <a href={`${dashboardUrl}?action=delegate`} className="action-button">
              👥 Delegate
            </a>
            <a href={`${dashboardUrl}?action=snooze`} className="action-button">
              ⏰ Snooze
            </a>
          </div>
        </div>
      </div>
      
      <div className="footer">
        <p className="footer-text">
          This notification was generated by your AI assistant. 
          <a href={dashboardUrl}> View in Dashboard</a>
        </p>
        
        <div className="footer-links">
          <a href="/settings" className="footer-link">Settings</a>
          <a href="/help" className="footer-link">Help</a>
          <a href={unsubscribeUrl} className="footer-link">Unsubscribe</a>
        </div>
      </div>
    </div>
  );
};

// Email styles as a separate object for easy customization
export const aiNotificationStyles = `
  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }
  
  body {
    font-family: 'Helvetica Neue', Arial, sans-serif;
    line-height: 1.6;
    color: #000000;
    background-color: #FFFFFF;
  }
  
  .email-container {
    max-width: 600px;
    margin: 0 auto;
    background-color: #FFFFFF;
  }
  
  .header {
    text-align: center;
    padding: 48px 24px 32px;
    border-bottom: 1px solid #F0F0F0;
  }
  
  .logo {
    font-size: 32px;
    font-weight: 700;
    color: #000000;
    margin-bottom: 8px;
  }
  
  .tagline {
    font-size: 16px;
    color: #666666;
    font-weight: 400;
  }
  
  .content {
    padding: 48px 24px;
  }
  
  .notification-header {
    text-align: center;
    margin-bottom: 32px;
  }
  
  .notification-icon {
    font-size: 48px;
    margin-bottom: 16px;
  }
  
  .greeting {
    font-size: 24px;
    font-weight: 600;
    color: #000000;
    margin-bottom: 16px;
  }
  
  .message {
    font-size: 16px;
    color: #333333;
    margin-bottom: 32px;
    text-align: center;
  }
  
  .email-details {
    background-color: #FAFAFA;
    padding: 20px;
    border-radius: 8px;
    margin-bottom: 32px;
  }
  
  .email-info {
    font-size: 14px;
    color: #333333;
  }
  
  .email-from,
  .email-subject {
    margin-bottom: 8px;
  }
  
  .ai-analysis {
    margin-bottom: 32px;
  }
  
  .ai-analysis h3 {
    font-size: 18px;
    font-weight: 600;
    color: #000000;
    margin-bottom: 16px;
  }
  
  .analysis-content {
    background-color: #F8F9FA;
    padding: 20px;
    border-radius: 8px;
    border-left: 4px solid #D4AF37;
  }
  
  .summary {
    font-size: 14px;
    color: #333333;
    margin-bottom: 16px;
    line-height: 1.6;
  }
  
  .suggested-action {
    font-size: 14px;
    color: #666666;
    font-style: italic;
  }
  
  .confidence-meter {
    margin-bottom: 32px;
  }
  
  .confidence-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 8px;
    font-size: 14px;
    font-weight: 600;
  }
  
  .confidence-score {
    font-weight: 700;
  }
  
  .confidence-bar {
    height: 8px;
    background-color: #E5E5E5;
    border-radius: 4px;
    overflow: hidden;
  }
  
  .confidence-fill {
    height: 100%;
    transition: width 0.3s ease;
  }
  
  .cta-section {
    text-align: center;
    margin-bottom: 32px;
  }
  
  .cta-button {
    display: inline-block;
    background-color: #D4AF37;
    color: #000000;
    text-decoration: none;
    padding: 16px 32px;
    border-radius: 8px;
    font-weight: 600;
    font-size: 16px;
    transition: all 0.3s ease;
  }
  
  .cta-button:hover {
    background-color: #B8941F;
    transform: translateY(-2px);
  }
  
  .quick-actions {
    margin-bottom: 32px;
  }
  
  .quick-actions h3 {
    font-size: 18px;
    font-weight: 600;
    color: #000000;
    margin-bottom: 16px;
    text-align: center;
  }
  
  .action-buttons {
    display: flex;
    gap: 12px;
    justify-content: center;
    flex-wrap: wrap;
  }
  
  .action-button {
    display: inline-block;
    background-color: #F8F9FA;
    color: #333333;
    text-decoration: none;
    padding: 12px 20px;
    border-radius: 6px;
    font-size: 14px;
    font-weight: 500;
    border: 1px solid #E5E5E5;
    transition: all 0.3s ease;
  }
  
  .action-button:hover {
    background-color: #E5E5E5;
    transform: translateY(-1px);
  }
  
  .footer {
    padding: 32px 24px;
    background-color: #FAFAFA;
    text-align: center;
    border-top: 1px solid #F0F0F0;
  }
  
  .footer-text {
    font-size: 14px;
    color: #666666;
    margin-bottom: 16px;
  }
  
  .footer-links {
    margin-bottom: 24px;
  }
  
  .footer-link {
    color: #D4AF37;
    text-decoration: none;
    margin: 0 12px;
    font-size: 14px;
  }
  
  .footer-link:hover {
    text-decoration: underline;
  }
  
  @media (max-width: 600px) {
    .content {
      padding: 32px 16px;
    }
    
    .header {
      padding: 32px 16px 24px;
    }
    
    .action-buttons {
      flex-direction: column;
      align-items: center;
    }
    
    .action-button {
      width: 100%;
      max-width: 200px;
      text-align: center;
    }
  }
`;

export default AINotification; 