name: ESLint & Vitest Coverage

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint (fail on warning)
        run: npx eslint . --max-warnings 0
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run Vitest with coverage
        run: npx vitest run --coverage
  
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Start application
        run: npm run start &
        env:
          PORT: 3000
      - name: Wait for application
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:3000/api/health; do sleep 2; done' || exit 1
      - name: Run smoke tests
        run: |
          echo "✅ Testing health endpoint..."
          curl -f http://localhost:3000/api/health && echo "✔ Health check passed"
          
          echo "✅ Testing status endpoint..."
          curl -f http://localhost:3000/api/status && echo "✔ Status check passed"
          
          echo "✅ Testing main page..."
          curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/ | grep -q "200\|307" && echo "✔ Main page accessible"
          
          echo "✅ All smoke tests passed!" 