name: Lighthouse CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build Next.js app
        run: npm run build
      - name: Start Next.js server
        run: npm run start &
      - name: Wait for server
        run: npx wait-on http://localhost:3000/dashboard
      - name: Run Lighthouse CI
        run: |
          npx -y @lhci/cli autorun \
            --collect.url=http://localhost:3000/dashboard \
            --assert.preset=lighthouse:recommended \
            --assert.assertions.categories.performance.score=\">=0.9" \
            --assert.assertions.categories.accessibility.score=\">=0.9" \
            --assert.assertions.categories.seo.score=\">=0.9" \
            --assert.assertions.categories.best-practices.score=\">=0.9" 